apiVersion: apps/v1
kind: Deployment
metadata:
  name: nftng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: front-end
  template:
    metadata:
      labels:
        component: front-end
    spec:
      containers:
        - name: client
          image: radianceobi/nftng-fe
          ports:
            - containerPort: 3000
